server:
    port: 8080

spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: ''
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            dll-auto: none
        properties:
            hibernate:
                format_sql: false